name: Test
on: workflow_dispatch
jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    #что делаем
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      - run: chmod +x ./gradlew && ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Checkout github pages with previous Allure reports
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Generate Allure test report
        uses: andgineer/allure-report@v3.4
        id: allure-report
        if: always()
        with:
          allure-results: build/allure-results
          website: gh-pages-dir
          reports-site-path: builds/tests

      - name: Publish Allure test report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}