name: Test
on: [push]
jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    #что делаем
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - uses: Xotabu4/selenoid-github-action@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew && ./gradlew clean test
